version: "3.7"

services:

  frontend:
    image: homemate-front
    container_name: 'homemate-front'
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - /app/node_modules
    ports: 
      - 8080:8080
    environment:
      PORT: 8080
      ESLINT_NO_DEV_ERRORS: true
      REACT_APP_API_URL: ${REACT_APP_API_URL}

volumes:
  node_modules: